/*
 * Copyright 2022 University of Michigan EECS183
 *
 * AI.cpp
 * Project UID 28eb18c2c1ce490aada441e65559efdd
 *
 * <#Names#>
 * <#Uniqnames#>
 *
 * Final Project - Elevators
 */

#include "AI.h"
#include <cassert>

// This file is used only in the Reach, not the Core.
// You do not need to make any changes to this file for the Core

/*
* Requires: buildingState is a valid state representing the current building
* Modifies: Nothing
* Effects:  Returns a string that represents the decision the AI makes
*           given the current state of the building, which it reads
*           from buildingState.
*           The string should share the exact format as a
*           human player's move input.
*/


string getAIMoveString(const BuildingState& buildingState) {
    
    // if the building is empty, return an empty string
    bool persons = false;
    for (int i = 0; i < NUM_FLOORS; i++) {
        _Floor floor = buildingState.floors[i];
        if (floor.numPeople != 0) {
            persons = true;
        }
    }
    if (persons == false) {
        return "";
    }
    // if an elevator has people on the floor its on & isn't servicing, then it will pickup
    for (int j = 0; j < NUM_ELEVATORS; j++) {
        _Elevator elevator = buildingState.elevators[j];
        if (buildingState.floors[elevator.currentFloor].numPeople > 0 && !elevator.isServicing) {
            if (j == 0) {
                return "e0p";
            }
            if (j == 1) {
                return "e1p";
            }
            if (j == 2) {
                return "e2p";
            }
        }
    }
    // if the building has people in it, then get an elevator (based on servicing status) to  move to that floor and service
    for (int k = 0; k < NUM_ELEVATORS; k++) {
        _Elevator elevator = buildingState.elevators[k];
        if (!elevator.isServicing) {
            for (int z = 0; z < NUM_FLOORS; z++) {
                _Floor floor = buildingState.floors[z];
                bool isfloorServiced = false;
                for (int m = 0; m < NUM_ELEVATORS; m++) {
                    if (buildingState.elevators[m].targetFloor == z) {
                        isfloorServiced = true;
                    }
                }
                if (floor.numPeople > 0 && !isfloorServiced) {
                    return "e" + to_string(k) + "f" + to_string(z);
                }
            }
        }
    }
    
    return "";
}

/*
* Requires: buildingState is a valid state representing the current building
*           move is a pickup move that was generated by getAIMoveString()
*           floorToPickup represents the floor the pickup move occurred.
* Modifies: Nothing
* Effects:  Returns a string representing which people indices
*           should be picked up. The string should share the exact format
*           as a human player's pickup list input.
*/

string getAIPickupList(const Move& move, const BuildingState& buildingState, 
                       const Floor& floorToPickup) {
    string upList = "";
    string downList = "";
    int numPeople = floorToPickup.getNumPeople();
    int numUpRequest = 0;
    int numDownRequest = 0;
    // get number of people with up and down requests & pickup either ups or downs
    // depending on majority rule
    for (int i = 0; i < numPeople; i++) {
        Person person = floorToPickup.getPersonByIndex(i);
        if (person.getTargetFloor() - person.getCurrentFloor() > 0) {
            upList += to_string(i);
            numUpRequest++;
        }
        if (person.getTargetFloor() - person.getCurrentFloor() < 0) {
            downList += to_string(i);
            numDownRequest++;
        }
    }
    if (numUpRequest > numDownRequest) {
        return upList;
    }
    return downList;
    //return "";
}
